services:
  app:
    image: node:latest
    container_name: base-template-api
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: base-template-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
